name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  test:
    name: "Unit Tests"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and Test (macOS)
        uses: sersoft-gmbh/xcodebuild-action@v4
        with:
          spm-package: "./"
          scheme: Package
          destination: platform=macOS
          action: test

      - name: Build and Test (iOS)
        uses: sersoft-gmbh/xcodebuild-action@v4
        with:
          spm-package: "./"
          scheme: Package
          destination: platform=iOS Simulator
          action: test
